### ISSUE TITLE
Add "Bare metal" workflow

### ISSUE THREAD

**Issue by yopu91** [andershedberg/embedded-development-course#1]
Before jumping into an RTOS I would recommend to send the learner down the path of getting small binaries to run on a ARM processor. For example using one of the Nucleo Development Boards.

https://www.st.com/en/evaluation-tools/stm32-nucleo-boards.html

This will teach the learner about things like:

- Compiling - armgcc
- Cross-compiling - why the cant run debug on their own computer without hardware or simulation
- bin, elf etc. See what files are needed to actually run a small micro-processor
- Connecting to a micro-processor, what is JTAG for example?
- Have some peripherals like LEDS that can be turned on without to much code or interrupt handling

All of these are things that Arduino and micropython might miss and are important to understand

**Comment by andershedberg** [comment]
Merged to master.
